export const elements = {
  screens: {
    start: document.getElementById("start-screen"),
    game: document.getElementById("game-screen"),
    results: document.getElementById("results-screen"),
  },
  startGameButton: document.getElementById("start-game-button"),
  playAgainButton: document.getElementById("play-again-button"),
  timerDisplay: document.getElementById("timer-display"),
  timeMeterFill: document.getElementById("time-meter-fill"),
  scoreDisplay: document.getElementById("score-display"),
  questionDisplay: document.getElementById("question-display"),
  flagDisplay: document.getElementById("flag-display"),
  feedbackText: document.getElementById("feedback-text"),
  answersGrid: document.getElementById("answers-grid"),
  historyPanel: document.querySelector(".history-panel"),
  historyList: document.getElementById("history-list"),
  finalCorrectAnswered: document.getElementById("final-correct-answered"),
  flagMarqueeTrack: document.getElementById("flag-marquee-track"),
  saveScoreForm: document.getElementById("save-score-form"),
  playerNameInput: document.getElementById("player-name"),
  saveScoreButton: document.getElementById("save-score-button"),
  saveStatus: document.getElementById("save-status"),
  leaderboard: {
    startList: document.getElementById("leaderboard-list"),
    startEmpty: document.getElementById("leaderboard-empty"),
    startStatus: document.getElementById("leaderboard-status"),
    resultsList: document.getElementById("results-leaderboard-list"),
    resultsEmpty: document.getElementById("results-leaderboard-empty"),
    resultsStatus: document.getElementById("results-leaderboard-status"),
  },
};
